 /* KIARA - Middleware for efficient and QoS/Security-aware invocation of services and exchange of messages
 *
 * Copyright (C) 2014 Proyectos y Sistemas de Mantenimiento S.L. (eProsima)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 *
 *
 * @file IDLText.java
 * This file contains IDL text.
 *
 * This file was generated by using the tool Kiaragen.
 *
 */
 
 
package org.fiware.kiara.struct;

/**
 * Class containing the IDL text for all the services.
 *
 * @author Kiaragen tool.
 *
 */
public final class IDLText {

    public static final String contents = "# 1 \"src/test/resources/idl/struct.idl\"\n# 1 \"<built-in>\"\n# 1 \"<command-line>\"\n# 1 \"/usr/include/stdc-predef.h\" 1 3 4\n# 1 \"<command-line>\" 2\n# 1 \"src/test/resources/idl/struct.idl\"\n\nstruct PrimitiveTypesStruct {\n char myChar;\n octet myByte;\n unsigned short myUShort;\n short myShort;\n unsigned long myUInt;\n long myInt;\n unsigned long long myULong;\n long long myLong;\n float myFloat;\n double myDouble;\n boolean myBoolean;\n string myString;\n string<5> myString5;\n};\n\nstruct InnerStruct {\n long innerLongAtt;\n string innerStringAtt;\n};\n\nstruct MidStruct {\n long midLongAtt;\n InnerStruct innerStructAtt;\n};\n\nstruct OuterStruct {\n long outerLongAtt;\n MidStruct midStructAtt;\n InnerStruct innerStructAtt;\n};\n\nservice StructService {\n    PrimitiveTypesStruct sendReceivePrimitives(PrimitiveTypesStruct value);\n    OuterStruct sendReceiveStruct(OuterStruct value);\n};\n";

    private IDLText() {
        throw new UnsupportedOperationException();
    }
}
