 /* KIARA - Middleware for efficient and QoS/Security-aware invocation of services and exchange of messages
 *
 * Copyright (C) 2014 Proyectos y Sistemas de Mantenimiento S.L. (eProsima)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 *
 *
 * @file .java
 * This file contains the class representing a user defined structure.
 *
 * This file was generated by using the tool Kiaragen.
 *
 */


package com.kiara.typesupport;

import java.util.List;
import java.util.ArrayList;
import java.util.Objects;

import com.kiara.serialization.impl.Serializable;
import com.kiara.serialization.impl.SerializerImpl;
import com.kiara.serialization.impl.CDRSerializer;
import com.kiara.transport.impl.TransportMessage;

/**
 * Class definition for the user defined type OuterStruct.
 *
 * @author Kiaragen tool.
 *
 */
public class OuterStruct implements Serializable {

	/*
	 *	Attributes
	 */

	private int outerLongAtt;

	private MidStruct midStructAtt;

	private InnerStruct innerStructAtt;


	/*
	 *	Default constructor
	 */
	public OuterStruct() {

		this.outerLongAtt = 0;

		this.midStructAtt = new MidStruct();

		this.innerStructAtt = new InnerStruct();
	}

	/*
	 * This method serializes a OuterStruct.
	 *
	 * @see com.kiara.serialization.impl.Serializable#serialize(com.kiara.serialization.impl.SerializerImpl, com.kiara.transport.impl.TransportMessage, java.lang.String)
	 */
	public void serialize(SerializerImpl impl, TransportMessage message, String name) {

		impl.serializeI32(message, name, this.outerLongAtt);

		impl.serialize(message, name, this.midStructAtt);

		impl.serialize(message, name, this.innerStructAtt);
	}

	/*
	 * This method deserializes a OuterStruct.
	 *
	 * @see com.kiara.serialization.impl.Serializable#deserialize(com.kiara.serialization.impl.SerializerImpl, com.kiara.transport.impl.TransportMessage, java.lang.String)
	 */
	public void deserialize(SerializerImpl impl, TransportMessage message, String name) {

			this.outerLongAtt = impl.deserializeI32(message, name);

		try {
			this.midStructAtt = impl.deserialize(message, name, MidStruct.class);
		} catch (InstantiationException | IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		try {
			this.innerStructAtt = impl.deserialize(message, name, InnerStruct.class);
		} catch (InstantiationException | IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/*
	 * @param other An object instance of Object
	 */
	 @Override
	public boolean equals(Object other) {
		boolean comparison = true;

		if (other instanceof OuterStruct) {

			comparison = comparison && (this.outerLongAtt == ((OuterStruct) other).outerLongAtt);

			comparison = comparison && this.midStructAtt.equals(((OuterStruct) other).midStructAtt);

			comparison = comparison && this.innerStructAtt.equals(((OuterStruct) other).innerStructAtt);

		}

		return comparison;
	}

	/*
	 *This method calculates the maximum size in CDR for this class.
	 *
	 * @param current_alignment Integer containing the current position in the buffer.
	 */
	public static int getMaxCdrSerializedSize(int current_alignment)
	{
	    int current_align = current_alignment;

	    current_align += 4 + CDRSerializer.alignment(current_align, 4);
	    current_align = MidStruct.getMaxCdrSerializedSize(current_align);
	    current_align = InnerStruct.getMaxCdrSerializedSize(current_align);

	    return current_align;
	}


	/*
	 * Method to get the attribute outerLongAtt.
	 */
	public int getouterLongAtt() {
		return this.outerLongAtt;
	}

	/*
	 * Method to set the attribute outerLongAtt.
	 */
	public void setouterLongAtt(int outerLongAtt) {
		this.outerLongAtt = outerLongAtt;
	}

	/*
	 * Method to get the attribute midStructAtt.
	 */
	public MidStruct getmidStructAtt() {
		return this.midStructAtt;
	}

	/*
	 * Method to set the attribute midStructAtt.
	 */
	public void setmidStructAtt(MidStruct midStructAtt) {
		this.midStructAtt = midStructAtt;
	}

	/*
	 * Method to get the attribute innerStructAtt.
	 */
	public InnerStruct getinnerStructAtt() {
		return this.innerStructAtt;
	}

	/*
	 * Method to set the attribute innerStructAtt.
	 */
	public void setinnerStructAtt(InnerStruct innerStructAtt) {
		this.innerStructAtt = innerStructAtt;
	}
}
