 /* KIARA - Middleware for efficient and QoS/Security-aware invocation of services and exchange of messages
 *
 * Copyright (C) 2014 Proyectos y Sistemas de Mantenimiento S.L. (eProsima)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 *
 *
 * @file ClientExample.java
 * This file contains the main client code example.
 *
 * This file was generated by using the tool Kiaragen.
 *
 */


package com.kiara.struct;

import com.kiara.client.Connection;
import com.kiara.Context;
import com.kiara.Kiara;
import com.kiara.serialization.Serializer;
import com.kiara.transport.Transport;

/**
 * Class that acts as the main client entry point.
 *
 * @author Kiaragen tool.
 *
 */
public class ClientExample {
	public static void main (String [] args) throws Exception {
		System.out.println("StructServiceClientExample");

		PrimitiveTypesStruct value = new PrimitiveTypesStruct();

				// Initialize your data here

		PrimitiveTypesStruct ret = null;

		Context context = Kiara.createContext();

		Transport transport = context.createTransport("tcp://127.0.0.1:9090");
		Serializer serializer = context.createSerializer("cdr");

		Connection connection = context.connect(transport, serializer);
		StructService client = connection.getServiceProxy(StructServiceClient.class);

		try {
			ret = client.sendReceivePrimitives(value);

				// Print or check the operation result here

		} catch (Exception ex) {
			System.out.println("Exception: " + ex.getMessage());
			return;
		}


	}
}
