 /* KIARA - Middleware for efficient and QoS/Security-aware invocation of services and exchange of messages
 *
 * Copyright (C) 2014 Proyectos y Sistemas de Mantenimiento S.L. (eProsima)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 *
 *
 * @file StructServiceExampleAsync.java
 * This file contains the main asynchronous interface for the defined operations.
 *
 * This file was generated by using the tool Kiaragen.
 *
 */


package com.kiara.struct;

import com.kiara.transport.impl.TransportMessage;
import com.kiara.client.AsyncCallback;
import com.kiara.serialization.impl.SerializerImpl;

/**
 * Interface containing the asynchronous method definition.
 *
 * @author Kiaragen tool.
 *
 */
public interface StructServiceAsync {

	public void sendReceivePrimitives(/*in*/ PrimitiveTypesStruct value, sendReceivePrimitives_AsyncCallback callback);

	public static abstract class sendReceivePrimitives_AsyncCallback implements AsyncCallback<PrimitiveTypesStruct> {
		public void process(TransportMessage message, SerializerImpl ser) {
			try {
				final Object messageId = ser.deserializeMessageId(message);
				PrimitiveTypesStruct result = ser.deserialize(message, "", PrimitiveTypesStruct.class);
				onSuccess(result);
			} catch (Exception ex) {
				onFailure(ex);
			}
		}
	}

	public void sendReceiveStruct(/*in*/ OuterStruct value, sendReceiveStruct_AsyncCallback callback);

	public static abstract class sendReceiveStruct_AsyncCallback implements AsyncCallback<OuterStruct> {
		public void process(TransportMessage message, SerializerImpl ser) {
			try {
				final Object messageId = ser.deserializeMessageId(message);
				OuterStruct result = ser.deserialize(message, "", OuterStruct.class);
				onSuccess(result);
			} catch (Exception ex) {
				onFailure(ex);
			}
		}
	}


}
