 /* KIARA - Middleware for efficient and QoS/Security-aware invocation of services and exchange of messages
 *
 * Copyright (C) 2014 Proyectos y Sistemas de Mantenimiento S.L. (eProsima)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 *
 *
 * @file StructServiceServantExample.java
 * This file contains the servant implementation.
 *
 * This file was generated by using the tool Kiaragen.
 *
 */


package com.kiara.struct;

/**
 * Class where the actual implementation of the procedures is located.
 *
 * @author Kiaragen tool.
 *
 */
class StructServiceServantExample extends StructServiceServant {

	/*!
	 * @brief This method implements the proxy part of the protocol for the operation sendReceivePrimitives.
	 *        It has to be implemented by the child classes.
	 */

	public PrimitiveTypesStruct sendReceivePrimitives (/*in*/ PrimitiveTypesStruct value) {

		// Your implementation code goes here

		return null;
	}

	/*!
	 * @brief This method implements the proxy part of the protocol for the operation sendReceiveStruct.
	 *        It has to be implemented by the child classes.
	 */

	public OuterStruct sendReceiveStruct (/*in*/ OuterStruct value) {

		// Your implementation code goes here

		return null;
	}



}
