 /* KIARA - Middleware for efficient and QoS/Security-aware invocation of services and exchange of messages
 *
 * Copyright (C) 2014 Proyectos y Sistemas de Mantenimiento S.L. (eProsima)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 *
 *
 * @file CalculatorExampleAsync.java
 * This file contains the main asynchronous interface for the defined operations.
 *
 * This file was generated by using the tool Kiaragen.
 *
 */
 


package org.fiware.kiara.calculator;

import org.fiware.kiara.transport.impl.TransportMessage;
import org.fiware.kiara.client.AsyncCallback;
import org.fiware.kiara.serialization.impl.SerializerImpl;

/**
 * Interface containing the asynchronous method definition.
 *
 * @author Kiaragen tool.
 *
 */
public interface CalculatorAsync {

	public void add(/*in*/ int n1, /*in*/ int n2, add_AsyncCallback callback);

	public static abstract class add_AsyncCallback implements AsyncCallback<Integer> {
		public void process(TransportMessage message, SerializerImpl ser) {
			try {
				final Object messageId = ser.deserializeMessageId(message);
				int result = ser.deserializeI32(message, "");
				onSuccess(result);
			} catch (Exception ex) {
				onFailure(ex);
			}
		}
	}


	public void subtract(/*in*/ int n1, /*in*/ int n2, subtract_AsyncCallback callback);

	public static abstract class subtract_AsyncCallback implements AsyncCallback<Integer> {
		public void process(TransportMessage message, SerializerImpl ser) {
			try {
				final Object messageId = ser.deserializeMessageId(message);
				int result = ser.deserializeI32(message, "");
				onSuccess(result);
			} catch (Exception ex) {
				onFailure(ex);
			}
		}
	}


	
}
