struct MyStruct {
	long myInt;
	string myString;
	long arrayInt[10][5];
	string<10> arrayString[10];
	sequence<long, 8> sequenceInt;
};

service TestService {

	MyStruct return_param_func(MyStruct param1, long param2);
	
	void only_param_func(MyStruct param1);
	
	MyStruct only_return_func();
	
	oneway void oneway_return_param_func(MyStruct param1, long param2);
	
	oneway void oneway_only_param_func(MyStruct param1);
	
	oneway void oneway_only_return_func();

};
