
struct PrimitiveTypesStruct {
	char myChar;
	octet myByte;
	unsigned short myUShort;
	short myShort;
	unsigned long myUInt;
	long myInt;
	unsigned long long myULong;
	long long myLong;
	float myFloat;
	double myDouble;
	boolean myBoolean;
	string myString;
	string<5> myString5;
};

struct InnerStruct {
	long innerLongAtt;
	string innerStringAtt;
};

struct MidStruct {
	long midLongAtt;
	InnerStruct innerStructAtt;
};

struct OuterStruct {
	long outerLongAtt;
	MidStruct midStructAtt;
	InnerStruct innerStructAtt;
};

service StructService {
    PrimitiveTypesStruct sendReceivePrimitives(PrimitiveTypesStruct value);
    OuterStruct sendReceiveStruct(OuterStruct value);
};
