 /* KIARA - Middleware for efficient and QoS/Security-aware invocation of services and exchange of messages
 *
 * Copyright (C) 2014 Proyectos y Sistemas de Mantenimiento S.L. (eProsima)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 *
 *
 * @file IDLText.java
 * This file contains IDL text.
 *
 * This file was generated by using the tool Kiaragen.
 *
 */
 
 
package org.fiware.kiara.exceptions;

/**
 * Class containing the IDL text for all the services.
 *
 * @author Kiaragen tool.
 *
 */
public final class IDLText {

    public static final String contents = "# 1 \"src/test/resources/idl/exceptions.idl\"\n# 1 \"<built-in>\"\n# 1 \"<command-line>\"\n# 1 \"/usr/include/stdc-predef.h\" 1 3 4\n# 1 \"<command-line>\" 2\n# 1 \"src/test/resources/idl/exceptions.idl\"\nexception DividedByZeroException {\n i32 code;\n string message;\n};\n\nexception FirstException {\n i32 code;\n string message;\n};\n\nexception SecondException {\n i32 code;\n string message;\n};\n\nservice Exceptions {\n  float32 divide (float32 n1, float32 n2) raises (DividedByZeroException);\n  i32 function() raises (FirstException, SecondException);\n};\n";

    private IDLText() {
        throw new UnsupportedOperationException();
    }
}
