package com.kiara.impl;

import com.kiara.server.Service;
import com.kiara.server.Servant;
import java.util.ArrayList;
import java.util.List;

public class ServiceImpl implements Service {
    private final List<Servant> generatedServants;

    public ServiceImpl() {
        generatedServants = new ArrayList<Servant>();
    }

    public void register(Object serviceImpl) {
        if (serviceImpl instanceof Servant) {
            // generated by IDL compiler
            generatedServants.add((Servant)serviceImpl);
        } else {
            // dynamic API starts here
            throw new UnsupportedOperationException("Dynamic API not implemented yet");
        }
    }

    public List<Servant> getGeneratedServants() {
        return generatedServants;
    }

}
